config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'forums#index'

  namespace :admin do
    constraints lambda { |req|
      current_user = User.find_by(id: req.session[:user_id])
      current_user&.admin?
    } do
      post 'delete_user/:user_id', to: 'actions#delete_user', as: :delete_user
    end
  end

  # /forums/forum-slug/sub-forum-slug/topic-slug
  # eg: /forums/music/ambient-experimental/sigur-ros
  # overwriting the path to achieve this structure of url

  resources :forums, param: :slug, path: 'forums'
  get '/forums/:forum_slug', to: 'sub_forums#index', as: :forum_sub_forums
  get '/forums/:forum_slug/:sub_forum_slug', to: 'sub_forums#show', as: :forum_sub_forum
  get '/forums/:forum_slug/:sub_forum_slug/edit', to: 'sub_forums#edit', as: :edit_forum_sub_forum

  # given the modified structure, forums/music/genre should show a list of topics instead of a list of forums
  get '/forums/:forum_slug/:sub_forum_slug', to: 'topics#index', as: :forum_sub_forum_topics
  post '/forums/:forum_slug/:sub_forum_slug/topics/new', to: 'topics#create', as: :new_sub_forum_topic
  get '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#show', as: :forum_sub_forum_topic
  get '/forums/:forum_slug/:sub_forum_slug/:topic_slug/edit', to: 'topics#edit', as: :edit_forum_sub_forum_topic
  patch '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#update'
  put '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#update'
  delete '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#destroy'

  post '/forums/:forum_slug/:sub_forum_slug/:topic_slug/comments', to: 'comments#create', as: :create_topic_comment

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sign-up', to: 'users#new', as: :user_sign_up
  post 'sign-up', to: 'users#create', as: :user_create
  get '/users/profile/:username', to: 'users#show', as: :user_show
  patch '/users/profile/edit/:username', to: 'users#update', as: :user_update
  delete '/users/profile/edit/:username/avatar', to: 'users#delete_avatar', as: :user_delete_avatar
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :forum
  belongs_to :user
  belongs_to :sub_forum
  has_many :comments
  has_many :user_topic_receipts

  validates :slug, uniqueness: true
  validates :title, uniqueness: { case_sensitive: false }

  before_save :generate_slug

  def to_param
    slug
  end

  def read?(user)
    # determines if the topic has been read by the current user
    return false unless user

    receipt = user_topic_receipts.where(user:)&.first
    return false unless receipt

    recent_activity < receipt.last_read
  end

  private

  def generate_slug
    self.slug = title.parameterize
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include Pagy::Backend

  # rubocop:disable Metrics/AbcSize
  def create
    topic = Topic.new(topic_params)

    if current_user.post_count > 5 && topic.save
      post_count = topic.user.post_count + 1
      topic.user.update(post_count:)
      topic.update(recent_activity: Time.current)

      redirect_to forum_sub_forum_topic_path(
        forum_slug: topic.sub_forum.forum.slug, sub_forum_slug: topic.sub_forum.slug, topic_slug: topic.slug
      )
    else
      respond_to do |format|
        format.html { render :new }
        format.turbo_stream
      end
    end
  end
  # rubocop:enable Metrics/AbcSize

  def index; end

  def show
    topic = Topic.find_by(slug: params[:topic_slug])
    @pagy, comments = pagy(Comment.where(topic:))

    set_meta_tags(
      title: topic.title,
      description: topic.body
    )

    read_receipt(topic) if current_user

    render :show, locals: { topic:, comments: }
  end

  private

  def read_receipt(topic)
    receipt = UserTopicReceipt.find_by(topic:, user: current_user)

    if receipt
      receipt.update_last_read
    else
      UserTopicReceipt.create(topic:, user: current_user, last_read: Time.current)
    end
  end

  def topic_params
    params.require(:topic).permit(:title, :body, :forum_id, :user_id, :sub_forum_id)
  end
end

app/views/topics/new.turbo_stream.erb
<%= turbo_stream.update 'error_message' do %>
  <div class='flex flex-row text-red-500'>
    something went wrong creating a topic, maybe this title already exists?
  </div>
<% end %>

app/views/topics/show.html.erb
<%= render 'forums/banner' %>
<!-- topic box -->
<div class='sticky z-10 flex w-full px-2 border-b top-10 bg-zinc-950 border-b-gray-700 md:px-14'>
  <div class='flex flex-row items-center justify-between w-full px-4 py-2 mx-auto space-x-4 lowercase border-l border-r border-gray-700 center text-slate-100'>
    <div>
      <%= link_to "<- #{topic.sub_forum.name}", forum_sub_forum_path(topic.sub_forum.forum, topic.sub_forum), class: 'hover:text-sky-500' %>
    </div>
    <%== pagy_nav(@pagy, link_extra: 'class="hover:text-sky-500 "') %>
  </div>
</div>
<div class='flex flex-col w-full border-b border-gray-700'>
  <div class='px-2 bg-zinc-950 md:px-14'>
    <% if params[:page].nil? || params[:page] == '1' %>
      <%= render partial: 'shared/post', locals: { message: topic, topic: }%>
    <% end %>
    <% comments.map do |comment| %>
      <%= render partial: 'shared/post', locals: { message: comment, topic: } %>
    <% end %>
  </div>
</div>
<div class='flex w-full px-2 border-b bg-zinc-950 border-b-gray-700 md:px-14'>
  <div class='flex flex-row items-center justify-between w-full h-10 px-4 py-2 mx-auto space-x-4 lowercase border-l border-r border-gray-700 text-slate-100'>
    <h1>leave a comment</h1>
    <%== pagy_nav(@pagy, link_extra: 'class="hover:text-sky-500 "')%>
  </div>
</div>
<!-- -->
<div id='error_message' class='flex flex-row'>
</div>
<% if current_user %>
  <%= form_with scope: :comment, url: create_topic_comment_path, local: true do |form| %>
    <div class='flex w-full px-2 border-b bg-zinc-950 border-b-gray-700 md:px-14'>
      <div class='flex flex-row w-full h-full px-4 py-2 space-x-4 border-l border-r border-gray-700 text-slate-100'>
        <div class='flex flex-col w-full p-4 space-y-4 md:flex-row md:space-x-8 md:space-y-0'>
          <div class='flex flex-col w-full space-y-4'>
            <%= form.text_area :body,
            class: 'border border-slate-700 px-4 w-full h-32 text-slate-50 text-xl bg-zinc-950 border-gray-700 focus:border-slate-500 focus:ring-1 focus:ring-slate-500',
            placeholder: ''
          %>
            <%= form.hidden_field :topic_id, value: topic.id %>
            <%= form.hidden_field :user_id, value: current_user.id %>
          </div>
          <div class='flex items-center justify-center basis-1/4'>
            <%= form.submit "submit",
            class: "bg-none border border-sky-500 hover:border-sky-700 hover:text-sky-700 text-sky-500 font-bold py-2 px-4 rounded-full cursor-pointer w-full h-16 md:h-24"
          %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<%= render 'forums/footer' %>