config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'forums#index'

  namespace :admin do
    constraints lambda { |req|
      current_user = User.find_by(id: req.session[:user_id])
      current_user&.admin?
    } do
      post 'delete_user/:user_id', to: 'actions#delete_user', as: :delete_user
    end
  end

  # /forums/forum-slug/sub-forum-slug/topic-slug
  # eg: /forums/music/ambient-experimental/sigur-ros
  # overwriting the path to achieve this structure of url

  resources :forums, param: :slug, path: 'forums'
  get '/forums/:forum_slug', to: 'sub_forums#index', as: :forum_sub_forums
  get '/forums/:forum_slug/:sub_forum_slug', to: 'sub_forums#show', as: :forum_sub_forum
  get '/forums/:forum_slug/:sub_forum_slug/edit', to: 'sub_forums#edit', as: :edit_forum_sub_forum

  # given the modified structure, forums/music/genre should show a list of topics instead of a list of forums
  get '/forums/:forum_slug/:sub_forum_slug', to: 'topics#index', as: :forum_sub_forum_topics
  post '/forums/:forum_slug/:sub_forum_slug/topics/new', to: 'topics#create', as: :new_sub_forum_topic
  get '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#show', as: :forum_sub_forum_topic
  get '/forums/:forum_slug/:sub_forum_slug/:topic_slug/edit', to: 'topics#edit', as: :edit_forum_sub_forum_topic
  patch '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#update'
  put '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#update'
  delete '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#destroy'

  post '/forums/:forum_slug/:sub_forum_slug/:topic_slug/comments', to: 'comments#create', as: :create_topic_comment

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sign-up', to: 'users#new', as: :user_sign_up
  post 'sign-up', to: 'users#create', as: :user_create
  get '/users/profile/:username', to: 'users#show', as: :user_show
  patch '/users/profile/edit/:username', to: 'users#update', as: :user_update
  delete '/users/profile/edit/:username/avatar', to: 'users#delete_avatar', as: :user_delete_avatar
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar
  has_many :user_topic_receipts
  has_many :topics

  validates :email, uniqueness: { case_sensitive: false }
  validates :username, uniqueness: { case_sensitive: false }

  def admin?
    role == 9001
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.new(user_params)

    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      respond_to do |format|
        format.html { render :new }
        format.turbo_stream
      end
    end
  end

  def delete_avatar
    user = User.find_by('username ILIKE ?', params[:username])
    user&.avatar&.purge_later

    if user
      redirect_to user_show_path(user.username)
    else
      redirect_to root_path
    end
  end

  def update
    user = User.find(params[:user_id])
    if user.update(user_params)
      redirect_to user_show_path, locals: { user: }
    else
      respond_to do |format|
        format.html { render :show }
        format.turbo_stream
      end
    end
  end

  def show
    user = User.find_by('username ILIKE ?', params[:username])

    if user
      render :show, locals: { user: }
    else
      # opting to just redirect to root w/o a notice, not sure if i care or not
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email, :password, :avatar, :display_location, :display_post_count, :location, :username
    )
  end
end

app/views/users/create.turbo_stream.erb
<%= turbo_stream.update 'error_message' do %>
  <div class='flex flex-row text-red-500'>
    username or email already in use
  </div>
<% end %>

app/views/users/new.html.erb
<%= render 'forums/banner' %>
<div class='flex w-full px-2 border-b bg-zinc-950 border-b-gray-700 md:px-14'>
  <div class='flex flex-row w-full h-full px-4 py-2 space-x-4 border-l border-r border-gray-700 text-slate-100'>
    <div id='error_message' class='flex flex-row'>
      create your account
    </div>
  </div>
</div>
<%= form_with scope: :user, url: user_create_path, local: true do |form| %>
  <div class='flex w-full px-2 border-b bg-zinc-950 border-b-gray-700 md:px-14'>
    <div class='flex flex-row w-full h-full px-4 py-2 space-x-4 border-l border-r border-gray-700 text-slate-700 '>
      <div class='flex flex-col w-full p-4 space-y-4 md:flex-row md:space-x-8 md:space-y-0 '>
        <div class='flex flex-col w-full space-y-4'>
          <%= form.text_field :username,
            class: 'w-full h-16 px-4 text-slate-50 text-xl bg-zinc-950 border border-slate-700 focus:border-slate-500 focus:ring-1 focus:ring-slate-500',
            placeholder: 'username'
          %>
          <%= form.email_field :email,
            class: 'w-full h-16 px-4 text-slate-50 text-xl bg-zinc-950 border border-slate-700 focus:border-slate-500 focus:ring-1 focus:ring-slate-500',
            placeholder: 'email'
          %>
          <%= form.password_field :password,
            class: 'w-full h-16 px-4 text-slate-50 text-xl bg-zinc-950 border border-slate-700 focus:border-slate-500 focus:ring-1 focus:ring-slate-500',
            placeholder: 'password'
          %>
        </div>
        <div class='flex items-center justify-center basis-1/4'>
          <%= form.submit "sign up",
            class: "bg-none border border-sky-500 hover:border-sky-700 hover:text-sky-700 text-sky-500 font-bold py-2 px-4 rounded-full cursor-pointer w-full h-16 md:h-24"
          %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<%= render 'forums/banner' %>
<!-- forum index box -->
<div class='sticky z-10 flex w-full px-2 border-b top-10 bg-zinc-950 border-b-gray-700 md:px-14'>
  <div class='flex flex-row items-center justify-between w-full px-4 py-2 mx-auto space-x-4 lowercase border-l border-r border-gray-700 center text-slate-100'>
    <%= link_to "<- home", forums_path, class: 'hover:text-sky-500 lowercase' %>
    edit profile
  </div>
</div>
<!-- topics index view -->
<div class='flex flex-col w-full border-b border-gray-700'>
  <div class='px-2 bg-zinc-950 md:px-14'>
    <div class='border-l border-r border-gray-700 bg-zinc-950 '>
      <div class='p-px overflow-hidden md:rounded-full ring-1 ring-gray-700'>
        <div class='flex flex-col border-gray-700 text-slate-100'>
          <%= form_with scope: :user, url: user_update_path(user_id: user.id), method: :patch, local: true do |form| %>
            <div class='px-4 py-6 border-gray-700 md:px-10' >
              <h1 class='text-2xl'>
                <%= current_user&.id == user.id ? 'edit profile' : "#{user.username}'s profile"%>
              </h1>
            </div>
            <div class='p-10 border-t border-gray-700 '>
              <div class='flex flex-row space-x-10'>
                <div class='flex flex-col '>
                  <div class="w-20 h-20 <%= 'border border-gray-700' if !user.avatar.attached? %>">
                    <%= image_tag user.avatar if user.avatar.attached? %>
                  </div>
                  <div class='mt-2 text-xs'>80x80 px</div>
                  <% if user.avatar.attached? && user.id == current_user&.id %>
                    <%= link_to 'remove avatar', user_delete_avatar_path(user.username), data: { turbo_method: :delete }, class: 'text-xs' %>
                  <% end %>
                </div>
                <div class='flex flex-col space-y-2'>
                  <div class='flex flex-row items-center space-x-2'>
                    <div><%= user.username %></div>
                  </div>
                  <div class='flex flex-row items-center space-x-2'>
                    <div class='flex flex-row items-center space-x-4'>
                      <div>location:</div>
                      <% if user.id == current_user&.id %>
                        <%= form.text_field :location,
                        value: user.location || '',
                        class: 'border border-slate-700 px-4 w-full h-8 text-slate-50 text-md bg-zinc-950 border-gray-700 focus:border-slate-500 focus:ring-1 focus:ring-slate-500',
                        placeholder: 'location'
                      %>
                      <% else %>
                        &nbsp;<%= "#{user.location}" %>
                      <% end %>
                    </div>
                  </div>
                  <div>posts: <%= user.post_count %></div>
                  <div>joined: <%= format_created_date(user) %></div>
                  <% if user.id == current_user&.id %>
                    <div class='flex flex-col space-y-2 md:space-x-4 md:flex-row '>
                      <div class='flex items-center space-x-2 '>
                        <%= form.check_box :display_post_count, checked: user.display_post_count? %>
                        <%= form.label :display_post_count, "display post count" %>
                      </div>
                      <div class='flex items-center space-x-2'>
                        <%= form.check_box :display_location, checked: user.display_location? %>
                        <%= form.label :display_location, "display location" %>
                      </div>
                    </div>
                    <div>
                      <%= form.file_field :avatar %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <div class='flex flex-row justify-end p-4 border-t border-gray-700 md:p-10'>
              <% if user.id == current_user&.id %>
                <%= form.submit "update profile",
                  class: "bg-none border border-sky-500 hover:border-sky-700 hover:text-sky-700 text-sky-500 font-bold py-2 px-4 rounded-full cursor-pointer w-full md:w-56 h-16 md:h-24"
                %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class='hidden w-full border-b md:flex bg-zinc-950 border-b-gray-700 px-14'>
  <div class='flex flex-row justify-end w-full h-10 px-4 py-2 space-x-4 border-l border-r border-gray-700 text-slate-100'>
  </div>
</div>
<%= render 'forums/footer' %>