config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'forums#index'

  namespace :admin do
    constraints lambda { |req|
      current_user = User.find_by(id: req.session[:user_id])
      current_user&.admin?
    } do
      post 'delete_user/:user_id', to: 'actions#delete_user', as: :delete_user
    end
  end

  # /forums/forum-slug/sub-forum-slug/topic-slug
  # eg: /forums/music/ambient-experimental/sigur-ros
  # overwriting the path to achieve this structure of url

  resources :forums, param: :slug, path: 'forums'
  get '/forums/:forum_slug', to: 'sub_forums#index', as: :forum_sub_forums
  get '/forums/:forum_slug/:sub_forum_slug', to: 'sub_forums#show', as: :forum_sub_forum
  get '/forums/:forum_slug/:sub_forum_slug/edit', to: 'sub_forums#edit', as: :edit_forum_sub_forum

  # given the modified structure, forums/music/genre should show a list of topics instead of a list of forums
  get '/forums/:forum_slug/:sub_forum_slug', to: 'topics#index', as: :forum_sub_forum_topics
  post '/forums/:forum_slug/:sub_forum_slug/topics/new', to: 'topics#create', as: :new_sub_forum_topic
  get '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#show', as: :forum_sub_forum_topic
  get '/forums/:forum_slug/:sub_forum_slug/:topic_slug/edit', to: 'topics#edit', as: :edit_forum_sub_forum_topic
  patch '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#update'
  put '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#update'
  delete '/forums/:forum_slug/:sub_forum_slug/:topic_slug', to: 'topics#destroy'

  post '/forums/:forum_slug/:sub_forum_slug/:topic_slug/comments', to: 'comments#create', as: :create_topic_comment

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sign-up', to: 'users#new', as: :user_sign_up
  post 'sign-up', to: 'users#create', as: :user_create
  get '/users/profile/:username', to: 'users#show', as: :user_show
  patch '/users/profile/edit/:username', to: 'users#update', as: :user_update
  delete '/users/profile/edit/:username/avatar', to: 'users#delete_avatar', as: :user_delete_avatar
end

app/models/sub_forum.rb
class SubForum < ApplicationRecord
  belongs_to :forum

  has_many :topics

  validates :slug, uniqueness: true

  before_save :generate_slug

  def to_param
    slug
  end

  def unread_posts?(user)
    # if stuff gets sluggish we should dip into caching here
    return false unless user

    # get the IDs of topics that the user has read receipts for in this sub-forum
    read_topic_ids = UserTopicReceipt.where(user:, topic_id: topics.select(:id)).pluck(:topic_id)

    # check for topics that have recent activity after the last_read_time
    last_read_time = UserTopicReceipt.where(user:, topic_id: read_topic_ids).maximum(:last_read)
    updated_topics_exist = topics.where('id IN (?) AND recent_activity > ?', read_topic_ids, last_read_time).exists?

    # check for new topics that the user has no read receipts for
    new_topics_exist = topics.where.not(id: read_topic_ids).exists?

    updated_topics_exist || new_topics_exist
  end

  private

  def generate_slug
    self.slug = name.parameterize
  end
end

app/controllers/sub_forums_controller.rb
class SubForumsController < ApplicationController
  include Pagy::Backend

  def show
    sub_forum = SubForum.find_by(slug: params[:sub_forum_slug])
    topics = Topic.where(sub_forum_id: sub_forum.id).order(recent_activity: :desc)
    @pagy, topics = pagy(topics)

    set_meta_tags(
      title: sub_forum.name,
      description: "check out topics about #{sub_forum.name.downcase}"
    )

    render :show, locals: { topics:, sub_forum: }
  end
end

app/views/sub_forums/index.html.erb
<%= render 'forums/banner' %>
<!-- forum index box -->
<div class='flex w-full border-b bg-zinc-950 border-b-gray-700 px-14'>
  <div class='flex flex-row justify-end w-full px-4 py-2 space-x-4 border-l border-r border-gray-700 text-slate-100'>
    <%= sub_forum.name %>
  </div>
</div>
<!-- topics index view -->
<div class='flex flex-col w-full border-b border-gray-700'>
  <div class='bg-zinc-950 px-14'>
    <div class='border-l border-r border-gray-700 bg-zinc-950 '>
      <div class='p-px overflow-hidden rounded-full bg-gradientTopRight ring-1 ring-gray-700'>
        <div class='flex flex-col border-gray-700 text-slate-100'>
          <!-- topics lists -->
          <div class="flex-col items-center justify-center w-full">
            <div class='px-10 py-6 border-gray-700' >
              <h1 class='text-2xl'>Topics</h1>
            </div>
            <% topics.each_with_index do |topic, index| %>
              <div class='flex flex-col px-10 py-4 space-y-2 border-t border-gray-700'>
                <h1 class='text-sm'>
                  <%= link_to topic.title, forum_sub_forum_topic_path(forum_slug: sub_forum.forum.slug, sub_forum_slug: sub_forum.slug) %>
                </h1>
                <h5 class='text-xs'>by <%= topic.user.username %>
                  <% if topic.created_at > 24.hours.ago %>
                    <%= time_ago_in_words(topic.created_at) + " ago" %>
                  <% else %>
                    on <%= topic.created_at.strftime("%b %d, %Y") %>
                  <% end %>
                </h5>
              </div>
              <% if index === topics.length - 1%>
                <div class='p-4 border-t border-gray-700 '>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class='flex w-full border-b bg-zinc-950 border-b-gray-700 px-14'>
  <div class='flex flex-row justify-end w-full h-10 px-4 py-2 space-x-4 border-l border-r border-gray-700 text-slate-100'>
  </div>
</div>
<%= render 'forums/footer' %>

app/views/sub_forums/show.html.erb
<%= render 'forums/banner' %>
<!-- forum index box -->
<div class='sticky z-10 flex w-full px-2 border-b top-10 bg-zinc-950 border-b-gray-700 md:px-14'>
  <div class='flex flex-row items-center justify-between w-full px-4 py-2 mx-auto space-x-4 lowercase border-l border-r border-gray-700 center text-slate-100'>
    <%= link_to "<- home", forums_path, class: 'hover:text-sky-500 lowercase' %>
    <%= sub_forum.name.downcase %>
  </div>
</div>
<!-- topics index view -->
<div class='flex flex-col w-full border-b border-gray-700'>
  <div class='px-2 bg-zinc-950 md:px-14'>
    <div class='border-l border-r border-gray-700 bg-zinc-950 '>
      <div class='p-px overflow-hidden md:rounded-full bg-gradientTopRight ring-1 ring-gray-700'>
        <div class='flex flex-col border-gray-700 text-slate-100'>
          <!-- topics lists -->
          <div class="flex-col items-center justify-center w-full">
            <div class='px-4 py-6 border-gray-700 md:px-10' >
              <h1 class='text-2xl'>topics</h1>
            </div>
            <% topics.each_with_index do |topic, index| %>
              <div class='flex w-full px-4 py-4 space-y-2 border-t border-gray-700 md:px-10 '>
                <div class='flex flex-row items-center justify-between w-full mx-auto '>
                  <div class='flex flex-col'>
                    <h1 class='<%= topic.read?(current_user) ? 'text-white' : 'text-sky-400 font-semibold' %> text-md md:text-sm'>
                      <%= link_to topic.title, forum_sub_forum_topic_path(forum_slug: sub_forum.forum.slug, sub_forum_slug: sub_forum.slug, topic_slug: topic.slug), class: 'hover:text-sky-500' %>
                    </h1>
                    <h5 class='text-xs'>by
                      <%= link_to topic.user.username, user_show_path(topic.user.username), class: 'hover:text-sky-500' %>
                      <%= format_created_date(topic) %>
                    </h5>
                  </div>
                  <% if !topic.comments.empty?  %>
                    <div class='flex flex-col items-end '>
                      <div class='text-sm'>
                        <%= link_to topic.comments.count == 1 ? "#{topic.comments.count} comment" : "#{topic.comments.count} comments",
                        forum_sub_forum_topic_path(forum_slug: sub_forum.forum.slug, sub_forum_slug: sub_forum.slug, topic_slug: topic.slug), class: 'hover:text-sky-500' %>
                      </div>
                      <div>
                        <h5 class='text-xs'>latest by
                          <%= link_to topic.comments.last.user.username, user_show_path(topic.comments.last.user.username), class: 'hover:text-sky-500' %>
                        </h5>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
              <% if index === topics.length - 1%>
                <div class='p-4 border-t border-gray-700 '>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class='hidden w-full border-b md:flex bg-zinc-950 border-b-gray-700 px-14'>
  <div class='flex flex-row justify-end w-full h-10 px-4 py-2 space-x-4 border-l border-r border-gray-700 text-slate-100'>
    <%== pagy_nav(@pagy, link_extra: 'class="lowercase hover:text-sky-500 "')%>
  </div>
</div>
<!-- add a comment box -->
<% if current_user %>
  <%= form_with scope: :topic, url: new_sub_forum_topic_path, local: true do |form| %>
    <div class='flex w-full px-2 border-b bg-zinc-950 border-b-gray-700 md:px-14'>
      <div class='flex flex-row w-full h-full px-4 py-2 space-x-4 border-l border-r border-gray-700 text-slate-100'>
        <div class='flex flex-col w-full p-4 space-y-4 md:flex-row md:space-x-8 md:space-y-0'>
          <div class='flex flex-col w-full space-y-4'>
            <%= form.text_field :title,
              class: 'border border-slate-700 px-4 w-full h-16 text-slate-50 text-xl bg-zinc-950 border-gray-700 focus:border-slate-500 focus:ring-1 focus:ring-slate-500',
              placeholder: 'new topic title'
            %>
            <%= form.text_area :body,
              class: 'border border-slate-700 px-4 w-full h-32 text-slate-50 text-xl bg-zinc-950 border-gray-700 focus:border-slate-500 focus:ring-1 focus:ring-slate-500',
              placeholder: 'topic post body'
            %>
            <%= form.hidden_field :sub_forum_id, value: sub_forum.id %>
            <%= form.hidden_field :forum_id, value: sub_forum.forum.id %>
            <%= form.hidden_field :user_id, value: current_user.id %>
          </div>
          <div class='flex items-center justify-center basis-1/4'>
            <%= form.submit "submit",
            class: "bg-none border border-sky-500 hover:border-sky-700 hover:text-sky-700 text-sky-500 font-bold py-2 px-4 rounded-full cursor-pointer w-full h-16 md:h-24"
          %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<%= render 'forums/footer' %>